"""fixregister

Revision ID: 1afa23478bd7
Revises: 8751a58d2f32
Create Date: 2016-05-10 13:45:57.737873

"""

# revision identifiers, used by Alembic.
revision = '1afa23478bd7'
down_revision = '8751a58d2f32'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_index('titile', table_name='articles')
    op.create_unique_constraint(None, 'articles', ['title'])
    op.drop_column('articles', 'titile')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('titile', mysql.VARCHAR(collation=u'utf8mb4_bin', length=64), nullable=True))
    op.drop_constraint(None, 'articles', type_='unique')
    op.create_index('titile', 'articles', ['titile'], unique=True)
    op.drop_column('articles', 'title')
    ### end Alembic commands ###
