"""update

Revision ID: 279239a98e96
Revises: d5480b6ea221
Create Date: 2016-05-09 14:15:13.577158

"""

# revision identifiers, used by Alembic.
revision = '279239a98e96'
down_revision = 'd5480b6ea221'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('real_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_name'),
    sa.UniqueConstraint('username')
    )
    op.add_column(u'articles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column(u'articles', 'user_id')
    op.drop_table('users')
    ### end Alembic commands ###
