"""fixregister

Revision ID: 8751a58d2f32
Revises: 279239a98e96
Create Date: 2016-05-10 13:09:58.744818

"""

# revision identifiers, used by Alembic.
revision = '8751a58d2f32'
down_revision = '279239a98e96'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(collation=u'utf8mb4_bin', length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    op.alter_column('articles', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
